#version: "3"
services:
  nuxt-app:
    container_name: nuxt_app
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      PG_HOST: ${PG_HOST}
      PG_USER: ${PG_USER}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_DATABASE: ${PG_DATABASE}
      PG_PORT: ${PG_PORT}
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - .:/app
      - /node_modules
    depends_on:
      - postgres-compose
    networks:
      - postgres-compose-network

  postgres-compose:
    container_name: postgres_compose
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "15432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - postgres-compose-network

  pgadmin-compose:
    container_name: pgadmin_compose
    image: dpage/pgadmin4
    ports:
      - "16543:80"
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - postgres-compose
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge

volumes:
  pgdata:
